# Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find [this](http://wiki.scipy.org/NumPy_for_Matlab_Users) tutorial useful to get started with Numpy.

## Importing Numpy

In [42]:
import numpy as np

## Arrays

In [43]:
a = np.array([1, 2, 3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])

<class 'numpy.ndarray'>
(3,)
1 2 3


In [44]:
a[0] = 5
print(a)

[5 2 3]


In [45]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


### Creating arrays

In [46]:
a = np.zeros((2, 2))
print(a)

[[ 0.  0.]
 [ 0.  0.]]


In [47]:
b = np.ones((1,2))
print(b)

[[ 1.  1.]]


In [48]:
c = np.full((2, 2), 7)
print(c)

[[7 7]
 [7 7]]


In [49]:
d = np.eye(2)
print(d)

[[ 1.  0.]
 [ 0.  1.]]


In [50]:
e = np.random.random((2, 2))
print(e)

[[ 0.15039778  0.87862185]
 [ 0.35804098  0.32429798]]


### Array Indexing

In [51]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [52]:
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [53]:
print(a[0, 1])

2


In [54]:
b[0,0] = 77

In [55]:
print(a[0,1])

77


Mixing integer indexing with slices yields an array of lower rank, while only using slices yields an array of the same rank as the original array.

row_r1 is a rank 1 view of the second row of a

In [56]:
row_r1 = a[1, :]
print(row_r1)

[5 6 7 8]


row_r2 is a rank 2 view of the second row of a

In [57]:
row_r2 = a[1:2, :]
print(row_r2)

[[5 6 7 8]]


### Array indexing 

In [58]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(a)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [59]:
# Array of indices
b = np.array([0,2,0,1])

print(a[np.arange(4), b])

[ 1  6  7 11]


In [60]:
a[np.arange(4), b] += 10

print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


### Boolean Indexing

In [61]:
a = np.array([[1,2], [3,4], [5,6]])
bool_idx = (a > 2)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [62]:
print(a[bool_idx])

[3 4 5 6]


In [63]:
print(a[a > 2])

[3 4 5 6]


## Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype.

In [64]:
x = np.array([1,2])
print(x.dtype)

int64


In [65]:
x = np.array([1,0, 2.0])
print(x.dtype)

float64


In [66]:
x = np.array([1,2], dtype=np.float32)
print(x.dtype)
print(x)

float32
[ 1.  2.]


Note that in deep learning computations, `float32` is most commonly used.

## Array Arithmetic 

In [67]:
x = np.array([[1,2], [3,4]], dtype=np.float32)
y = np.array([[5,6], [7,8]], dtype=np.float32)

Elementwise sum

In [71]:
print(x + y)
print(np.add(x,y))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]


Elementwise difference

In [72]:
print(x - y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


Elementwise product

In [73]:
print(x * y)
print(np.multiply(x,y))

[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]


Elementwise division

In [74]:
print(x/y)
print(np.divide(x,y))

[[ 0.2         0.33333334]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333334]
 [ 0.42857143  0.5       ]]


Elementwise squareroot

In [75]:
print(np.sqrt(x))

[[ 1.          1.41421354]
 [ 1.73205078  2.        ]]


Inner product of vectors

In [76]:
v = np.array([1,2])
w = np.array([3,4])
print(np.dot(v,w))

11


In [77]:
print(np.dot(x,y))

[[ 19.  22.]
 [ 43.  50.]]


Summing arrays over columns (axis = 0)

In [78]:
x

array([[ 1.,  2.],
       [ 3.,  4.]], dtype=float32)

In [79]:
np.sum(x, axis=0)

array([ 4.,  6.], dtype=float32)

Summing arrays over row (axis = 1)

In [81]:
np.sum(x, axis=1)

array([ 3.,  7.], dtype=float32)

## Transposing

In [82]:
x = np.array([[1,2], [3,4]])
print(x)

[[1 2]
 [3 4]]


In [83]:
print(x.T)

[[1 3]
 [2 4]]


The transpose of a rank 1 array does nothing:

In [84]:
v = np.array([1,2,3])
print(v)
print(v.T)

[1 2 3]
[1 2 3]


## Broadcasting

Suppose the task is to add a constant vector to each row of the matrix. This is a slow method of doing it, because of the explicit loops in Python.

In [85]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

In [86]:
v = np.array([1,0,1])

In [87]:
y = np.empty_like(x)

In [88]:
for i in range(4):
    y[i, :] = x[i, :] + v

In [90]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [89]:
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

Notice that we can achieve the equivalent by performing an elementwise summation of the vector `v` duplicated for each row.

In [91]:
vv = np.tile(v, (4, 1))
print(x + vv)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


numpy broadcasting allows us to perform this computation without actually creating multiple copies of `v`.

In [93]:
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Here are some applications of broadcasting:

### Computing the outer product

In [95]:
v = np.array([1,2,3])
w = np.array([4,5])

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]
